- hosts: monitor
  name: Install Monitoring
  vars:
    alerts_receiver_email: example-email@example.com
    alerts_sender_email: example-email@example.com
    alerts_sender_password: Sender_p@ssw0rd
    scylla_cluster_name: testcluster
    scylla_monitoring_archive_url: https://github.com/scylladb/scylla-monitoring/archive/refs/tags/4.8.0.tar.gz
    scylla_monitoring_dashboards_versions:
    - '2024.1'
  roles:
    - scylla-ansible-roles/ansible-scylla-monitoring
